version: 0.0
os: linux
files:
  - source: /webapp/target/webapp.war
    destination: /opt/docker/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root


