version: 0.0
os: linux
files:
  - source: /webapp/target/webapp.war
    destination: /opt/docker/
  - source: Dockerfile
    destination: /opt/docker/
hooks:
  AfterInstall:
    - location: scripts/start_docker
      timeout: 300
      runas: root
    - location: scripts/docker_services
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/stop_servers
      timeout: 300
      runas: root


