#!/bin/bash
cd /opt/docker
if [ -e webapp.war  ]; then rm webapp.war; fi
if [ -e Dockerfile  ]; then rm Dockerfile; fi
isExistApp = `pgrep dockerd`
if [[ -n  $isExistApp ]]; then
    service docker stop        
fi
